[package]
name = "wordsolve"
version = "0.1.0"
authors = ["Naftuli Kay <me@naftuli.wtf>"]
edition = "2018"

[dependencies]
structopt = "0.2"
smol_str = "0.1.11"
hashbrown = { version = "0.4.0", features = ["rayon"] }
zstd = "0.4.24"
rayon = "1.0.3"
